name: 'Secret Serfer'
description: 'Looking for Secrets in current commit. It can create a report in JUnit Format.'
inputs:
  args:
    description: |
      Arguments to be passed

    required: true

runs:
  using: "docker"
  image: 'Dockerfile'
  args:
  - ${{ inputs.args }}


#    - run: python -m pip install --upgrade pip
#      shell: bash
#    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
#      shell: bash
#    - run: trufflehog3 --no-history --branch ${GITHUB_REF#refs/heads/} -r rules.yaml -f yaml --line-numbers ${GITHUB_WORKSPACE} | yaml2junit.py
#      shell: bash
          
          