name: 'Secret Serfer'
author: Andrey Shelkov
description: 'Looking for Secrets in current commit. It can create a report in JUnit Format.'
inputs:
  args:
    description: |
      usage: trufflehog3 [options]

      Find secrets in your codebase.

      Allowed optional arguments:
        -v, --verbose      enable verbose logging {-v, -vv, -vvv}
        -o, --output       write report to file
        --no-entropy       disable entropy checks

    required: false
    
  targets:
    description: |
      Paths to git repository files 
      which should be scanned by trufflehog3
    required: true

  report:
    description: |
      Name of JUnit test results file
    required: false

runs:
  using: "docker"
  image: 'Dockerfile'
  args:
  - ${{ inputs.args }}

  env:
    TARGETS: ${{ inputs.targets }}
    REPORT: ${{ inputs.report }}
          
          